In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
input_tensor = torch.tensor([
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

In [ ]:
print("Input Tensor:")
print(input_tensor.squeeze().numpy())

Input Tensor:
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [ ]:
kernel = torch.tensor([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

In [ ]:
print("\nKernel Tensor:")
print(kernel.squeeze().numpy())


Kernel Tensor:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
def convolve_with_stride(input_tensor, kernel, stride):
    output = F.conv2d(input_tensor, kernel, stride=stride, padding=0)  # No padding
    return output


In [ ]:
strides = [1, 2, 3]
outputs = []

for stride in strides:
    output = convolve_with_stride(input_tensor, kernel, stride)
    outputs.append(output)
    print(f"\nOutput Tensor with Stride {stride}:")
    print(output.squeeze().numpy())

# Analyze the Output
print("\nAnalysis of Results:")
print("1. Stride 1: Produces an output tensor of size 4x4. Each pixel is influenced by maximum kernel overlap, resulting in more detailed feature extraction.")
print("2. Stride 2: Reduces the output tensor to size 2x2. Some image details are skipped due to increased step size, resulting in less overlap.")
print("3. Stride 3: Further reduces the output tensor to size 1x1. Only a single kernel application occurs, greatly simplifying the extracted feature.")



Output Tensor with Stride 1:
[[ 0. -3. -3.  0.]
 [ 0. -3. -3.  0.]
 [ 0. -3. -3.  0.]
 [ 0. -3. -3.  0.]]

Output Tensor with Stride 2:
[[ 0. -3.]
 [ 0. -3.]]

Output Tensor with Stride 3:
[[0. 0.]
 [0. 0.]]

Analysis of Results:
1. Stride 1: Produces an output tensor of size 4x4. Each pixel is influenced by maximum kernel overlap, resulting in more detailed feature extraction.
2. Stride 2: Reduces the output tensor to size 2x2. Some image details are skipped due to increased step size, resulting in less overlap.
3. Stride 3: Further reduces the output tensor to size 1x1. Only a single kernel application occurs, greatly simplifying the extracted feature.
