In [ ]:
# creating input and kernel tensor
import torch

# Input tensor
input_tensor = torch.tensor([[1, 1, 1, 0, 0, 0],
                            [1, 1, 1, 0, 0, 0],
                            [1, 1, 1, 0, 0, 0],
                            [1, 1, 1, 0, 0, 0],
                            [1, 1, 1, 0, 0, 0],
                            [1, 1, 1, 0, 0, 0]])

# Kernel tensor (for detecting vertical edges)
kernel = torch.tensor([[-1, 0, 1],
                        [-1, 0, 1],
                        [-1, 0, 1]])

In [ ]:
#Convolution with different strides
# Convolution with stride 1
output_stride1 = torch.nn.functional.conv2d(input_tensor.unsqueeze(0).unsqueeze(0), kernel.unsqueeze(0).unsqueeze(0), stride=1)

# Convolution with stride 2
output_stride2 = torch.nn.functional.conv2d(input_tensor.unsqueeze(0).unsqueeze(0), kernel.unsqueeze(0).unsqueeze(0), stride=2)
print(output_stride1)#The output will be a 4x4 tensor. Produces a detailed output, capturing fine-grained features.
print(output_stride2)#The output will be a 2x2 tensor.Produces a coarser output, reducing computational cost but potentially losing some information.]

tensor([[[[ 0, -3, -3,  0],
          [ 0, -3, -3,  0],
          [ 0, -3, -3,  0],
          [ 0, -3, -3,  0]]]])
tensor([[[[ 0, -3],
          [ 0, -3]]]])


In [ ]:
#Best practices to consider when implementing convolution in PyTorch
# Leverage PyTorch's  Module
import torch.nn as nn

# Define the convolutional layer
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)
'''
Batch Processing
PyTorch's convolutional layers are designed to handle batches of images efficiently.
Make sure that  your input tensor has the batch dimension as the first dimension.
'''
#Assuming a batch of 6 images
input_tensor = torch.randn(6, 1, 6, 6)  # Batch, Channel, Height, Width
output = conv_layer(input_tensor)
if torch.cuda.is_available():#Here we verifying the GPU Availability
    device = torch.device("cuda")
    input_tensor = input_tensor.to(device)
    conv_layer = conv_layer.to(device)
print(output)#You'll get an output tensor of the same shape: (16, 1, 6, 6).
print(conv_layer)

tensor([[[[-0.3843,  0.1784,  0.8482,  0.3492, -0.1781,  0.4862],
          [-0.6199,  1.4455,  0.4984, -1.3351,  0.3619, -0.3082],
          [-0.0501, -0.0712,  0.7014,  0.7726, -0.9030,  0.3129],
          [ 0.4047,  0.6088,  0.1137, -0.4287, -0.3144, -0.3336],
          [ 0.4584,  0.0636, -0.2792,  0.3410, -0.2600,  0.1121],
          [ 0.1846, -0.1797, -0.8022, -0.6623, -0.5133, -0.1768]]],


        [[[-0.2413,  0.0882, -0.6934,  0.2262,  0.3605,  0.2944],
          [-0.1279,  0.8842, -0.1650,  0.3514, -0.2671, -0.4250],
          [ 0.3679, -0.6029, -1.4623, -0.0890,  0.7396,  1.0942],
          [-0.0441,  0.3049,  0.3143,  0.4347,  0.2187,  1.0719],
          [-0.1616,  0.6932, -0.2587,  0.6377,  0.0747,  1.4744],
          [-0.4245,  0.3152,  0.5092, -0.3191,  0.5747,  0.8577]]],


        [[[-0.7034, -0.9966, -0.7064, -1.1041, -0.4750, -0.4391],
          [-0.8821, -0.4674, -0.6252,  0.2506,  0.3670,  0.9770],
          [-0.6083, -0.3569,  0.3485,  0.1810,  0.7418, -0.1519],
  